### ISSUE TITLE
Calling GetError causes an InvalidCastException

### ISSUE THREAD

**Issue by mellinoe** [WaveEngine/WebGL.NET#5]
First of all, thanks for the bindings, they have been quite fun to play around with. I've been able to get up and running pretty smoothly, but calling `WebGLRenderingContextBase.GetError` seems to cause an error like the following:

```
Uncaught (in promise) Error: System.InvalidCastException: Specified cast is not valid.
  at WebGLDotNET.WebGLRenderingContextBase.InvokeForBasicType[T] (:8000/System.String method, System.Object[] args) [0x00000] in E:\projects\WebGL.NET\src\WebGLDotNET\WebGL.Backend.cs:155 
  at :8000/WebGLDotNET.WebGLRenderingContextBase.GetError () [0x00000] in E:\projects\WebGL.NET\src\WebGLDotNET\WebGL.cs:792 
```

Without knowing too much about how the wasm layer is working, it's hard to diagnose this one.

**Comment by mellinoe** [comment]
I noticed the same problem was also happening in the `GetUniformBlockIndex` function, which is  more of a problem for my library. I was able to fix it by changing the implementation to the following, and the same works for GetError.

```diff
- public uint GetUniformBlockIndex(WebGLProgram program, string uniformBlockName) => InvokeForBasicType<uint>("getUniformBlockIndex", program, uniformBlockName);
+ public uint GetUniformBlockIndex(WebGLProgram program, string uniformBlockName) => (uint)InvokeForBasicType<int>("getUniformBlockIndex", program, uniformBlockName);
```

**Comment by MarcosCobena** [comment]
Hi Eric,

When I saw you were reporting issues a smile rendered in my face :-) Thanks in advance for them.

You reached one of the multiple calls we've still not tested. Although we started by calling functions by hand we moved into a transpiler to generate the entire API, adding such stuff like the one you found. So, I'll look into this and surely add such cast.

Thanks again,

—Marcos
