### ISSUE TITLE
BindBufferRange doesn't work ("size <= 0")

### ISSUE THREAD

**Issue by mellinoe** [WaveEngine/WebGL.NET#6]
When calling BindBufferRange, there seems to be some kind of problem with how the parameters are passed down to WebGL. I can't tell if this is a problem in the binding layer, in how the parameters are marshaled, or in mono itself. Calling BindBufferRange with seemingly-valid parameters (including a non-zero size), yields this error:

```
Invalid type 11 to mono_unbox_int
[.WebGL-0000022851F1FAA0]GL ERROR :GL_INVALID_VALUE : glBindBufferRange: size <= 0
```

The first is an error emitted by mono itself when invoking BindBufferRange, and the second is a message from Chrome's WebGL diagnostics. They certainly seem related.

I also noticed that the last two parameter types of [BindBufferRange](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/bindBufferRange)  both map to `long long`, according to [this chart](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Types). The bindings marshal these as `uint` and `ulong`, however, which doesn't match my intuition. Then again, I am not very familiar with this arena, and only one error seems to be getting emitted about parameter casting by mono.

**Comment by MarcosCobena** [comment]
Hi again Eric,

`BindBufferRange` has this signature:

`public void BindBufferRange(uint target, uint index, WebGLBuffer buffer, uint offset, ulong size) => Invoke("bindBufferRange", target, index, buffer, offset, size);`

, which was auto-generated from this definition —according to [our copy](https://github.com/WaveEngine/WebGL.NET/blob/ab82649a1d2d54f79249b2ba0f71b7cfe1c283f1/src/WebIDLToCSharp/webgl2.idl):

`void bindBufferRange(GLenum target, GLuint index, WebGLBuffer? buffer, GLintptr offset, GLsizeiptr size);`

So yes, [our type mapping](https://github.com/WaveEngine/WebGL.NET/blob/ab82649a1d2d54f79249b2ba0f71b7cfe1c283f1/src/WebIDLToCSharp/Program.cs#L89) is currently incorrect:
```
{ "GLintptr", "uint" },
{ "GLsizei", "int" },
```

I'll look into this one as well.

Thanks!

—Marcos

**Comment by kjpou1** [comment]
Marcos,

Since it is a 64 bit integer it will probably need to be mapped to a double.  WebAssembly does not support `long` or `ulong`.

The following may work.

```

{ "GLint64", "double" },
{ "GLsizeiptr", "double" },
{ "GLuint64", "double" },

```

**Comment by MarcosCobena** [comment]
Hi guys,

As you can see in the commit, just `GLsizeiptr` becomes `double` —thanks @kjpou1 for pointing this out! If you @mellinoe tells us it works fine for you we'll consider moving the rest as well.

By the way, you can see I've added a quite poor unit tests stuff, because haven't found anything better now, but would be great if you @mellinoe could share in some way what you achieve, as a new samples for instance.

Thanks in advance!
